# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{devise_couch_potato}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andi Bade"]
  s.date = %q{2010-10-11}
  s.description = %q{this gem enables devise for couch_potato models}
  s.email = %q{andi@galaxycats.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "devise_couch_potato.gemspec",
     "lib/devise/orm/couch_potato.rb",
     "lib/devise/orm/couch_potato/schema.rb",
     "lib/devise_couch_potato.rb",
     "test/helper.rb",
     "test/test_devise_couch_potato.rb"
  ]
  s.homepage = %q{http://github.com/galaxycats/devise_couch_potato}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{use couch_potato with devise}
  s.test_files = [
    "test/helper.rb",
     "test/test_devise_couch_potato.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

